Starting the script...
Traceback (most recent call last):
File "c:\Users\kacper.murat\Desktop\PLIKI\Projekty\Script_aggregator\v1\scripts\Przypadki_testowe\error.py", line 7, in <module>
main()
File "c:\Users\kacper.murat\Desktop\PLIKI\Projekty\Script_aggregator\v1\scripts\Przypadki_testowe\error.py", line 3, in main
Error during script execution: 'utf-8' codec can't decode byte 0xb3 in position 37: invalid start byte
